// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BNiEKWG5ZB_bLJsu_3G8O_0eKFLN0mI',
    appId: '1:259247542084:web:cdcb1756d8eeb64230d111',
    messagingSenderId: '259247542084',
    projectId: 'project-vivid',
    authDomain: 'project-vivid.firebaseapp.com',
    storageBucket: 'project-vivid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi8DNH1q5rcirAR33QSDOYjTCuOv8jrLM',
    appId: '1:259247542084:android:9eeb500e9a523ac630d111',
    messagingSenderId: '259247542084',
    projectId: 'project-vivid',
    storageBucket: 'project-vivid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwbsDXzJthuOqc3CQ6u7LsbAfFOePUmY',
    appId: '1:259247542084:ios:8632495b9fa411e230d111',
    messagingSenderId: '259247542084',
    projectId: 'project-vivid',
    storageBucket: 'project-vivid.appspot.com',
    iosClientId: '259247542084-a9av5s88ga6cujrkjlf21tit0l35mvlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectvivid',
  );
}
